### ISSUE TITLE
own data example not working

### ISSUE THREAD

**Issue by blubbundbla** [McTavishLab/physcraper#131]
command from https://github.com/McTavishLab/physcraper/blob/main/docs/mds/Tutorial.md:
physcraper_run.py -tf tests/data/tiny_test_example/test.tre -tfs newick -a tests/data/tiny_test_example/test.fas --taxon_info tests/data/tiny_test_example/main.json -as fasta -o owndata

Error message:
usage: physcraper_run.py [-h] [-s STUDY_ID] [-t TREE_ID] [-tl TREE_LINK]
                         [-a ALIGNMENT] [-as ALN_SCHEMA] [-db BLAST_DB]
                         [-o OUTPUT] [-bs BOOTSTRAP_REPS] [-tx TAXONOMY]
                         [-c CONFIGFILE] [-e EMAIL] [-re RELOAD_FILES] [-r]
                         [-tag TAG] [-tb] [-no_est] [-ev EVAL]
                         [-hl HITLIST_LEN] [-tp TRIM_PERC]
                         [-rl RELATIVE_LENGTH] [-spn SPECIES_NUMBER]
                         [-nt NUM_THREADS] [-de DELAY] [-st SEARCH_TAXON]
physcraper_run.py: error: unrecognized arguments: tests/data/tiny_test_example/test.tre newick --taxon_info tests/data/tiny_test_example/main.json

**Comment by snacktavish** [comment]
That command runs ok for me. It looks like you may have an older version installed? 
Try (from the physcraper directory)
```
git checkout main
git pull
pip install -r requirements.txt
pip install -e .
physcraper_run.py -tf tests/data/tiny_test_example/test.tre -tfs newick -a tests/data/tiny_test_example/test.fas --taxon_info tests/data/tiny_test_example/main.json -as fasta -o owndata
```
Let me know if that works!

**Comment by blubbundbla** [comment]
Yes, works with the newer version...
