### ISSUE TITLE
reviewer 1 - comment 3 - Anaconda/virtualenv

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/physcraper#143]
"Anaconda/virtualenv installation instructions should be added and these requirements should be specified in the README."

**Comment by LunaSare** [comment]
These are already on the installation instructions section at [readthedocs](https://physcraper.readthedocs.io/en/latest/install.html#option-1-install-physcraper-using-conda)
But we can surely make that more clear.

- [ ] add to readme
- [ ] highlight on installation instructions

**Comment by LunaSare** [comment]
added to readme 6cd952abc17129ff904e0c9b6786d1a567fe3640 and highlighted on installation instructions at readthedocs 58c441ed1e03181d7b27bec5f88b7b3bc3c5a932
