### ISSUE TITLE
bugs!

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/physcraper#15]
- handling taxonomy in local blast - current hack is list of GIs
- identical sequences are sneaking in. How?
- zombie taxa?

**Comment by blubbundbla** [comment]
all three bugs are solved by now. 

- taxonomy in local blast is using the taxdump files from ncbi
- identical sequences are being removed early on, if they are identical and from the same taxon
- zombie taxa problem was likely solved when we solved the prune_short()/reconcile() issue
