### ISSUE TITLE
error with search_taxon ott:417957

### ISSUE THREAD

**Issue by LunaSare** [McTavishLab/physcraper#181]
Running 

`time physcraper_run.py --study_id pg_1600 --tree_id tree3231 --search_taxon ott:417957  --treebase --bootstrap_reps 2 --output pg_1600 > output.txt`

```
Traceback (most recent call last):
  File "/usr/local/bin/physcraper_run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/project/physcraper/bin/physcraper_run.py", line 237, in <module>
    data_obj = generate_ATT_from_phylesystem(study_id =study_id,
  File "/project/physcraper/physcraper/opentree_helpers.py", line 361, in generate_ATT_from_phylesystem
    if search_taxon.isinstance(list):
AttributeError: 'str' object has no attribute 'isinstance'
```

**Comment by LunaSare** [comment]
It seems it does not like the "ott:" prefix.
I tried the following and it is running (it output the taxon names for the constrained blast search)

`physcraper_run.py --study_id pg_423 --tree_id tree2857 --search_taxon 187219 --treebase 'nexus' --bootstrap_reps 2 --output pg_423`

**Comment by snacktavish** [comment]
Fixed in https://github.com/McTavishLab/physcraper/commit/1c9888b25f5d0389f9e1db3aa60fd5f08a8ce791
