### ISSUE TITLE
Setup Automatic testing on TravisCI. 

### ISSUE THREAD

**Issue by Carreau** [McTavishLab/physcraper#26]
There seem to be some instruction on how to test physcraper and test scripts. 

There are several services that provide free compute to run unit-testing on github, mostly [Travis-CI](https://travis-ci.org/), and [Circle-CI](https://circleci.com/), they both have the ups and down, but should be relatively easy to setup.  They  usually not only test the master branch, but also can test Pull-requests, to ensure there is no regressions. With a bit of effort test could also be run on multiple platform to make sure the code works both on Linux, macOS and windows. 

They also have the option to re-run the test once per week to make sure there is no regressions due to changes to upstream libraries. 

I'm happy to help set that up, that would also make sure that the instruction on how to setup testing are correct and do no rely on a particular configuration of a particular machine. 

So far I've managed to get the test running on my machine, but most of them are failing, so I'm unsure if it is my setup or some mistake in the software of the tests themselves.

**Comment by blubbundbla** [comment]
I have added more things to the travis.yml file. It's running mostly, only that I do not find the issue with export path from papara. Someone an idea?

https://github.com/McTavishLab/physcraper/blob/3274009211472d8e8c9f8622e43e85d748192aa8/.travis.yml#L17
