### ISSUE TITLE
create account on https://readthedocs.org

### ISSUE THREAD

**Issue by Carreau** [McTavishLab/physcraper#35]
@blubbundbla  and @snacktavish , can you create and account on https://readthedocs.org and give me your usernames so that I can make you admins for the doc pages ?

**Comment by blubbundbla** [comment]
my username at readthedocs is blubbundbla

**Comment by Carreau** [comment]
I've added you on two physcraper and test-physcraper so you can mess around with the test repo if you wish to. You shouldn't need to do anything though.

**Comment by snacktavish** [comment]
I'm snacktavish! Thanks for setting this up

**Comment by Carreau** [comment]
You're now admin on both test-physcraper and physcraper.
