### ISSUE TITLE
taxon namesspace error

### ISSUE THREAD

**Issue by shchurch** [McTavishLab/physcraper#4]
Hi, there are some problems I am running into with the `taxon_namespace` in `generate_streamed_alignment( )`. I have come across this on two datasets now (though on other datasets it is not an issue).

For one dataset I chased down the error I was getting, which was reported at 
`assert treed_taxa.issubset(aln_ids)`
There is one taxon that is in the `tre` but not the `aln`, that is causing this assertion to fail. I looked into this taxon - it happens to be one that had low coverage. It passed the filter the first time through but then following realignment with papara, was too low and was added to the prune list to be filtered out.

However at this step in `reconcile( )`
`self.tre.prune_taxa(prune)
 self.aln.remove_sequences(prune)`
the taxon gets pruned form `aln` but not from `tre`, because the taxon IDs are no longer the same.

In aln 
`<Taxon 0x2ab0c792b910 'otu259115'>`
In tre 
`(<Taxon 0x2ab0b4979050 'otu259115'>)>,` 

Looks like there is a problem reestablishing the taxon namespace following papara. I got a slightly different error in another dataset, but also with taxon_namespace, but I did not get a chance to dig into it:

`dendropy.utility.error.ImmutableTaxonNamespaceError: Taxon 'otuPS2441' cannot be added to an immutable TaxonNamespace`
Hope this helps!

**Comment by snacktavish** [comment]
Ah, thanks! I'll take a look.

**Comment by snacktavish** [comment]
I'm getting that error too - digging into it, hope to have it sorted out soon.
