### ISSUE TITLE
Profile alignment in muscle?

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/physcraper#78]
https://github.com/McTavishLab/physcraper/blob/dev/physcraper/scrape.py#L947

Muscle align not very efficient for large data sets,

**Comment by LunaSare** [comment]
Implementing these http://www.drive5.com/muscle/muscle.html

**Comment by LunaSare** [comment]
Done and merged, yay! https://github.com/McTavishLab/physcraper/pull/82
