### ISSUE TITLE
new sequences with duplicated otuPS tag

### ISSUE THREAD

**Issue by LunaSare** [McTavishLab/physcraper#81]
In `docs/examples/minimal_example.py` 
Data taken from precooked example in `tests/test_multi.py`

**Comment by snacktavish** [comment]
Should fixed in aeb316dc66a5ae97e6e491385d198455c0b785ca 
Included in PR https://github.com/McTavishLab/physcraper/pull/82

**Comment by LunaSare** [comment]
Fixed on https://github.com/McTavishLab/physcraper/pull/82!
