### ISSUE TITLE
manually downloaded alignment not read

### ISSUE THREAD

**Issue by LunaSare** [McTavishLab/physcraper#95]
Alignment file downloaded from treeBASE directly <http://purl.org/phylo/treebase/phylows/matrix/TB2:M2478?format=nexus>

Running:

`physcraper_run.py -s pg_2827 -t tree6577 -a M2478.nex -o pg_2827_tree6577`

Getting this error:

```
  File "physcraper/venv-physcraper/bin/physcraper_run.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/luna/pj_physcraper/physcraper/bin/physcraper_run.py", line 110, in <module>
    assert(args.aln_schema)
AssertionError
```

**Comment by snacktavish** [comment]
Added a better error message
